apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  labels:
    name: twocontainerspod-example
    serviceName: twocontainerspod
    id: "2" #1/2
    app_ad: "1" #application differentiator
    nb_pods: "2" #number of pods in the application
    update: "True" #True to measure latency and bandwidth before each application deployment
    timelimit: "10" #the maximum delay for the scheduling algorithm to provide pod affectation 
spec:
  schedulerName: setpodnet-scheduler
  containers:
  - name: redis
    image: redis:5.0.3-alpine
    #resources:
      #limits:
        #memory: 6000Mi
        #cpu: 8
      #requests:
        #memory: 6000Mi
        #cpu: 8